"""Add viewed_movies column

Revision ID: 84d9dbc898aa
Revises: 6a7c7960e980
Create Date: 2023-10-15 14:25:03.959042

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '84d9dbc898aa'
down_revision = '6a7c7960e980'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie_infor', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(display_width=20),
               type_=sa.Integer(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('name',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.alter_column('url',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('time',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('genre',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('release_time',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('directors',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('writers',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('starts',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('movie_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('viewed_movies', postgresql.JSON(astext_type=Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie_users', schema=None) as batch_op:
        batch_op.drop_column('viewed_movies')

    with op.batch_alter_table('movie_infor', schema=None) as batch_op:
        batch_op.alter_column('starts',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('writers',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('directors',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('release_time',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('genre',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('time',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('url',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(display_width=20),
               nullable=True,
               autoincrement=True)

    # ### end Alembic commands ###
